version: '3'

services:
  client:
    build: .
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - task-manager
networks:
  task-manager:
    driver: bridge
volumes:
  mongo-database:
    driver: local
